version: "3.7"

services:
  db:
    image: postgres:13.4
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
      - ./logs:/var/log
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  web:
    container_name: django_app
    build: ./
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/code/
      - static:/static
    entrypoint: /code/entrypoint.sh

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./:/code/
      - static:/static
    depends_on:
      - web
    restart: on-failure

  redis:
    image: "redis:alpine"
    restart: always
    container_name: "redis"

  celery:
    build: ./
    env_file:
      - .env
    depends_on:
      - redis
      - web
    volumes:
      - ./:/code/
    command: ['celery', '-A', 'orders', 'worker', '-l', 'info']

volumes:
  pgdata:
  static: