version: "3.7"

services:
  db:
    image: postgres:13.4
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
      - ./logs:/var/log
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  web:
    container_name: django_app
    build: ./
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - static:/static
    entrypoint: /code/entrypoint.sh

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - web
    restart: on-failure

volumes:
  pgdata:
  static: