version: "3.7"

volumes:
  pgdata:

services:
  db:
    image: postgres:13.4
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./logs:/var/log
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

#  web:
#    build: ./
#    depends_on:
#      - db
#    restart: always
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    volumes:
#      - .:/app
